version: "3"
services:
    database:
        image: kartoza/postgis:12.0
        environment:
            POSTGRES_DBNAME: dev_db
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_PASS: dev_password
            POSTGRES_USER: dev_user
        volumes:
            - database-data:/var/lib/postgresql/data/
        ports:
            - 5432:5432

volumes:
    database-data:
        driver: local
